"""
Generate a self-contained interactive HTML report and save it to logs/.

The report contains:
  1. Signals overview (confidence bar chart for all recommendations)
  2. Individual stock/ETF charts for every BUY/SELL ticker
  3. Equity curve (if there are closed trades)
"""

from __future__ import annotations

from datetime import datetime, timezone
from src.utils import now_et, fmt_et
from pathlib import Path
from typing import Dict, List, Optional as Opt

from loguru import logger

from src.models import Recommendation, TickerSignal
from src.charts.builder import (
    PLOTLY_AVAILABLE,
    build_signals_overview,
    build_stock_chart,
    build_equity_curve,
)

REPORTS_DIR = Path("logs")


def save_html_report(
    recommendations: List[Recommendation],
    performance: dict | None = None,
    label: str | None = None,
    signals_by_ticker: Opt[Dict[str, TickerSignal]] = None,
) -> Path | None:
    """
    Build a full interactive HTML report and write it to logs/.

    Returns the file path, or None if plotly is not available.
    """
    if not PLOTLY_AVAILABLE:
        return None
    if not recommendations:
        return None

    REPORTS_DIR.mkdir(exist_ok=True)

    ts = label or datetime.now(timezone.utc).strftime("%Y-%m-%d_%H%M")
    out_path = REPORTS_DIR / f"report_{ts}.html"

    try:
        import plotly.io as pio
        sections: list[str] = []

        # ------------------------------------------------------------------
        # 1. Signals overview
        # ------------------------------------------------------------------
        overview_fig = build_signals_overview(recommendations, signals_by_ticker)
        if overview_fig:
            sections.append(pio.to_html(overview_fig, full_html=False, include_plotlyjs=False))

        # ------------------------------------------------------------------
        # 2. Per-ticker charts (BUY/SELL only to keep the report focused)
        # ------------------------------------------------------------------
        actionable = [r for r in recommendations if r.action in ("BUY", "SELL")]
        for rec in sorted(actionable, key=lambda r: r.confidence, reverse=True):
            fig = build_stock_chart(rec.ticker, rec)
            if fig:
                sections.append(pio.to_html(fig, full_html=False, include_plotlyjs=False))

        # ------------------------------------------------------------------
        # 3. Equity curve
        # ------------------------------------------------------------------
        closed = (performance or {}).get("closed_trades", [])
        eq_fig = build_equity_curve(closed)
        if eq_fig:
            sections.append(pio.to_html(eq_fig, full_html=False, include_plotlyjs=False))

        if not sections:
            return None

        # ------------------------------------------------------------------
        # Assemble full HTML
        # ------------------------------------------------------------------
        now_str = fmt_et(now_et())
        action_summary = ", ".join(
            f"{r.action} {r.ticker}" for r in sorted(actionable, key=lambda r: r.confidence, reverse=True)
        )
        html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>LLM Trader — {now_str}</title>
  <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
  <style>
    body {{
      font-family: 'Segoe UI', Arial, sans-serif;
      background: #0f172a;
      color: #e2e8f0;
      margin: 0;
      padding: 24px;
    }}
    h1 {{ color: #f8fafc; font-size: 22px; margin-bottom: 4px; }}
    .subtitle {{ color: #94a3b8; font-size: 14px; margin-bottom: 28px; }}
    .section {{ margin-bottom: 36px; }}
    .disclaimer {{
      color: #475569;
      font-size: 12px;
      text-align: center;
      margin-top: 40px;
      border-top: 1px solid #1e293b;
      padding-top: 16px;
    }}
  </style>
</head>
<body>
  <h1>LLM Trader — {now_str}</h1>
  <div class="subtitle">
    {len(recommendations)} tickers analysed &nbsp;&bull;&nbsp;
    Signals: {action_summary if action_summary else 'none'}
  </div>
  {''.join(f'<div class="section">{s}</div>' for s in sections)}
  <div class="disclaimer">
    Generated by LLM Trader &nbsp;&bull;&nbsp;
    Not financial advice. Always do your own research.
  </div>
</body>
</html>"""

        out_path.write_text(html, encoding="utf-8")
        logger.info(f"[charts] HTML report saved → {out_path}")
        return out_path

    except Exception as e:
        logger.error(f"[charts] Failed to build HTML report: {e}")
        return None