"""Send recommendation digest emails via SMTP."""

import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional

from jinja2 import Template
from loguru import logger

from config import settings
from src.models import Recommendation, Scorecard


ACTION_COLOR = {
    "BUY": "#16a34a",
    "SELL": "#dc2626",
    "HOLD": "#2563eb",
    "WATCH": "#d97706",
}

POS_COLOR = "#16a34a"
NEG_COLOR = "#dc2626"

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; background: #f3f4f6; padding: 20px; }
    .card { background: white; border-radius: 8px; padding: 16px; margin: 12px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 4px; color: white; font-weight: bold; font-size: 14px; }
    .ticker { font-size: 22px; font-weight: bold; color: #111; }
    .direction { font-size: 13px; color: #555; margin-left: 8px; }
    .rationale { color: #374151; margin-top: 8px; font-size: 14px; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 24px; }
    h1 { color: #111827; }
    h2 { color: #111827; font-size: 18px; margin-top: 28px; }
    table.perf { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    table.perf th, table.perf td { padding: 8px 10px; text-align: left; font-size: 13px; border-bottom: 1px solid #eee; }
    table.perf th { background: #f9fafb; color: #374151; }
    .muted { color: #6b7280; font-size: 13px; }
  </style>
</head>
<body>
  <h1>Market Recommendations — {{ generated_at }}</h1>
  <p>Analysed {{ total }} tickers. Actionable signals below.</p>

  {% for rec in recommendations %}
  <div class="card">
    <span class="ticker">{{ rec.ticker }}</span>
    <span class="direction">{{ rec.direction }} &bull; conf {{ (rec.confidence * 100)|int }}%</span>
    <br><br>
    <span class="badge" style="background:{{ colors[rec.action] }}">{{ rec.action }}</span>
    <p class="rationale">{{ rec.rationale }}</p>
  </div>
  {% endfor %}

  {{ performance_html | safe }}

  <div class="footer">
    Generated by LLM Trader &bull; {{ generated_at }}<br>
    <em>This is not financial advice. Always do your own research.</em>
  </div>
</body>
</html>
"""


def _fmt_pct(x: float) -> str:
    return f"{x:+.2%}"


def _color_span(x: float) -> str:
    color = POS_COLOR if x >= 0 else NEG_COLOR
    return f'<span style="color:{color}; font-weight:bold;">{_fmt_pct(x)}</span>'


def _performance_html(scorecard: Optional[Scorecard]) -> str:
    """Render the realized-returns section. Empty string if nothing to show."""
    if scorecard is None:
        return ""

    parts: List[str] = ['<h2>Performance — realized returns of past calls</h2>']

    if scorecard.total_graded == 0:
        parts.append(
            f'<p class="muted">No recommendations have matured yet '
            f'({scorecard.total_logged} logged). Returns will appear here once a '
            f'few sessions have closed.</p>'
        )
        return "\n".join(parts)

    # Horizon summary table (directional BUY/SELL calls only).
    parts.append('<table class="perf">')
    parts.append(
        '<tr><th>Horizon</th><th>Hit rate</th><th>Calls</th>'
        '<th>Avg return</th><th>Best</th><th>Worst</th></tr>'
    )
    for h in scorecard.horizons:
        if h.graded == 0:
            parts.append(
                f'<tr><td>{h.horizon_days}d</td>'
                f'<td colspan="5" class="muted">no graded calls yet</td></tr>'
            )
            continue
        parts.append(
            f"<tr><td>{h.horizon_days}d</td>"
            f"<td>{h.hit_rate:.0%}</td>"
            f"<td>{h.hits}/{h.graded}</td>"
            f"<td>{_color_span(h.avg_aligned_return)}</td>"
            f"<td>{_color_span(h.best)}</td>"
            f"<td>{_color_span(h.worst)}</td></tr>"
        )
    parts.append('</table>')
    parts.append(
        '<p class="muted">Returns are close-to-close, signed by the call '
        '(BUY +, SELL −): positive means the call was directionally right.</p>'
    )

    # Recently graded individual calls.
    if scorecard.recent:
        parts.append('<table class="perf" style="margin-top:12px;">')
        parts.append(
            '<tr><th></th><th>Ticker</th><th>Call</th><th>Horizon</th>'
            '<th>Return</th><th>Dated</th></tr>'
        )
        for g in scorecard.recent:
            mark = "✓" if g.hit else "✗"
            mark_color = POS_COLOR if g.hit else NEG_COLOR
            parts.append(
                f'<tr><td style="color:{mark_color}; font-weight:bold;">{mark}</td>'
                f"<td>{g.ticker}</td>"
                f"<td>{g.action}</td>"
                f"<td>{g.horizon_days}d</td>"
                f"<td>{_color_span(g.aligned_return)}</td>"
                f'<td class="muted">{g.generated_at.strftime("%Y-%m-%d")}</td></tr>'
            )
        parts.append('</table>')

    return "\n".join(parts)


def _performance_text(scorecard: Optional[Scorecard]) -> List[str]:
    """Plain-text version of the performance section."""
    if scorecard is None:
        return []

    lines = ["", "PERFORMANCE — realized returns of past calls", "-" * 44]
    if scorecard.total_graded == 0:
        lines.append(
            f"No recommendations have matured yet ({scorecard.total_logged} logged)."
        )
        return lines

    for h in scorecard.horizons:
        if h.graded == 0:
            lines.append(f"{h.horizon_days}d: no graded calls yet")
            continue
        lines.append(
            f"{h.horizon_days}d: hit rate {h.hit_rate:.0%} ({h.hits}/{h.graded})  "
            f"avg {_fmt_pct(h.avg_aligned_return)}  "
            f"best {_fmt_pct(h.best)}  worst {_fmt_pct(h.worst)}"
        )
    lines.append("(close-to-close, signed by the call: + means the call was right)")

    if scorecard.recent:
        lines.append("")
        lines.append("Recently graded:")
        for g in scorecard.recent:
            mark = "OK " if g.hit else "MISS"
            lines.append(
                f"  [{mark}] {g.ticker:<6} {g.action:<5} {g.horizon_days}d  "
                f"{_fmt_pct(g.aligned_return)}  ({g.generated_at.strftime('%Y-%m-%d')})"
            )
    return lines


def _send(subject: str, text_body: str, html_body: str) -> bool:
    """Low-level SMTP send shared by all email types."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.smtp_user
        msg["To"] = ", ".join(settings.recipients_list)
        msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.sendmail(
                settings.smtp_user,
                settings.recipients_list,
                msg.as_string(),
            )

        logger.info(f"Email sent to {settings.recipients_list}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def send_recommendations(
    recommendations: List[Recommendation],
    total_analysed: int = 0,
    scorecard: Optional[Scorecard] = None,
) -> bool:
    """Render and send the recommendation email, including realized performance."""
    if not recommendations:
        logger.warning("No recommendations to send.")
        return False

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html_body = Template(HTML_TEMPLATE).render(
        recommendations=recommendations,
        generated_at=now_str,
        total=total_analysed or len(recommendations),
        colors=ACTION_COLOR,
        performance_html=_performance_html(scorecard),
    )

    # Plain text fallback
    lines = [f"Market Recommendations — {now_str}", ""]
    for rec in recommendations:
        lines.append(f"{rec.ticker}: {rec.action} ({rec.direction}, {rec.confidence:.0%} conf)")
        lines.append(f"  {rec.rationale}")
        lines.append("")
    lines.extend(_performance_text(scorecard))
    text_body = "\n".join(lines)

    subject = f"LLM Trader | {now_str} | {len(recommendations)} signals"
    return _send(subject, text_body, html_body)


def send_performance_report(scorecard: Scorecard) -> bool:
    """Send a standalone performance report (no new recommendations)."""
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html_body = (
        f"<!DOCTYPE html><html><head><style>"
        f"body {{ font-family: Arial, sans-serif; background:#f3f4f6; padding:20px; }}"
        f"h1 {{ color:#111827; }} h2 {{ color:#111827; font-size:18px; }}"
        f"table.perf {{ width:100%; border-collapse:collapse; background:white; }}"
        f"table.perf th, table.perf td {{ padding:8px 10px; text-align:left; font-size:13px; border-bottom:1px solid #eee; }}"
        f"table.perf th {{ background:#f9fafb; }} .muted {{ color:#6b7280; font-size:13px; }}"
        f"</style></head><body><h1>LLM Trader — Performance Report</h1>"
        f"<p class='muted'>{now_str}</p>{_performance_html(scorecard)}</body></html>"
    )
    text_body = "\n".join(
        [f"LLM Trader — Performance Report ({now_str})"] + _performance_text(scorecard)
    )
    subject = f"LLM Trader | Performance Report | {now_str}"
    return _send(subject, text_body, html_body)
