"""Send recommendation digest emails via SMTP."""

import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from jinja2 import Template
from loguru import logger
from typing import List
from config import settings
from src.models import Recommendation


ACTION_COLOR = {
    "BUY": "#16a34a",
    "SELL": "#dc2626",
    "HOLD": "#2563eb",
    "WATCH": "#d97706",
}

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; background: #f3f4f6; padding: 20px; }
    .card { background: white; border-radius: 8px; padding: 16px; margin: 12px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .badge { display: inline-block; padding: 4px 10px; border-radius: 4px; color: white; font-weight: bold; font-size: 14px; }
    .ticker { font-size: 22px; font-weight: bold; color: #111; }
    .direction { font-size: 13px; color: #555; margin-left: 8px; }
    .rationale { color: #374151; margin-top: 8px; font-size: 14px; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 24px; }
    h1 { color: #111827; }
    h2 { color: #374151; font-size: 16px; margin-top: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  </style>
</head>
<body>
  <h1>Actionable Signals — {{ generated_at }}</h1>
  <p>Analysed {{ total }} tickers. BUY/SELL signals below.</p>

  {% if stocks %}
  <h2>Stocks</h2>
  {% for rec in stocks %}
  <div class="card">
    <span class="ticker">{{ rec.ticker }}</span>
    <span class="direction">{{ rec.direction }} &bull; conf {{ (rec.confidence * 100)|int }}%</span>
    <br><br>
    <span class="badge" style="background:{{ colors[rec.action] }}">{{ rec.action }}</span>
    <p class="rationale">{{ rec.rationale }}</p>
  </div>
  {% endfor %}
  {% endif %}

  {% if etfs %}
  <h2>ETFs / Markets</h2>
  {% for rec in etfs %}
  <div class="card">
    <span class="ticker">{{ rec.ticker }}</span>
    <span class="direction">{{ rec.direction }} &bull; conf {{ (rec.confidence * 100)|int }}%</span>
    <br><br>
    <span class="badge" style="background:{{ colors[rec.action] }}">{{ rec.action }}</span>
    <p class="rationale">{{ rec.rationale }}</p>
  </div>
  {% endfor %}
  {% endif %}

  <div class="footer">
    Generated by LLM Trader &bull; {{ generated_at }}<br>
    <em>This is not financial advice. Always do your own research.</em>
  </div>
</body>
</html>
"""


def send_recommendations(recommendations: List[Recommendation], total_analysed: int = 0) -> bool:
    """Render and send the recommendation email."""
    if not recommendations:
        logger.warning("No recommendations to send.")
        return False

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    stocks = sorted([r for r in recommendations if r.type == "STOCK"], key=lambda x: x.confidence, reverse=True)
    etfs = sorted([r for r in recommendations if r.type == "ETF"], key=lambda x: x.confidence, reverse=True)

    html_body = Template(HTML_TEMPLATE).render(
        stocks=stocks,
        etfs=etfs,
        generated_at=now_str,
        total=total_analysed or len(recommendations),
        colors=ACTION_COLOR,
    )

    # Plain text fallback
    lines = [f"Actionable Signals — {now_str}", ""]
    if stocks:
        lines.append("STOCKS")
        for rec in stocks:
            lines.append(f"  {rec.ticker}: {rec.action} ({rec.direction}, {rec.confidence:.0%})")
            lines.append(f"    {rec.rationale}")
            lines.append("")
    if etfs:
        lines.append("ETFs / MARKETS")
        for rec in etfs:
            lines.append(f"  {rec.ticker}: {rec.action} ({rec.direction}, {rec.confidence:.0%})")
            lines.append(f"    {rec.rationale}")
            lines.append("")
    text_body = "\n".join(lines)

    buys = [r.ticker for r in recommendations if r.action == "BUY"]
    subject = f"LLM Trader | {now_str} | BUY: {', '.join(buys) if buys else 'none'}"

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.smtp_user
        msg["To"] = ", ".join(settings.recipients_list)
        msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.sendmail(
                settings.smtp_user,
                settings.recipients_list,
                msg.as_string(),
            )

        logger.info(f"Email sent to {settings.recipients_list}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
